Header header

# Workstation layout

# Provides information about workstation location
# in map frame and various points of interest in
# local frame

# Workstation ID
string workstation_id

# Workstation pose in map frame
geometry_msgs/Pose pose_workstation

# RB_Kairos Docking pose for pickup in local frame
geometry_msgs/Pose pose_rb_kairos

# Worker pose for pickup in local frame
geometry_msgs/Pose pose_worker